name: pyepwmorph
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - pip:
    - -e .
    - pytest>=7.0
    - pytest-cov>=4.0
    - bump2version>=1.0
    - build>=0.10
    - twine>=4.0
    - black>=23.0
    - isort>=5.0
    - flake8>=6.0